In [1]:
from torchrecsys.datasets import InteractionsDataset, SequenceDataset
from torchrecsys.models import BaseModel, NeuralCF
from torchrecsys.task import Ranking
from torchrecsys.layers import BruteForceLayer
from torchrecsys.utils import feature_catalog
from torchrecsys import Trainer
import pandas as pd

from torch.utils.data import DataLoader

In [2]:
ratings = pd.read_csv("ml-100k/ratings.csv").rename(columns={"userId": "user", "movieId": "item"})
movies = pd.read_csv("ml-100k/movies.csv").rename(columns={"movieId": "item"})
users = ratings[["user"]].drop_duplicates()


print(movies)
movies['title'], uniques = pd.factorize(movies['title'])
movies['genres'], uniques = pd.factorize(movies['genres'])

movies['title'] = movies.title.astype('category')
movies['genres'] = movies.genres.astype('category')

        item                                      title  \
0          1                           Toy Story (1995)   
1          2                             Jumanji (1995)   
2          3                    Grumpier Old Men (1995)   
3          4                   Waiting to Exhale (1995)   
4          5         Father of the Bride Part II (1995)   
...      ...                                        ...   
9737  193581  Black Butler: Book of the Atlantic (2017)   
9738  193583               No Game No Life: Zero (2017)   
9739  193585                               Flint (2017)   
9740  193587        Bungo Stray Dogs: Dead Apple (2018)   
9741  193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Drama|Romance  
4                              

In [3]:
dataset = InteractionsDataset(ratings, users, movies, target_column=True)
train = DataLoader(dataset, batch_size=5)

In [4]:
for u in train:
    break

In [5]:
dataset.data_schema["interactions"]

[610, 193609]

In [6]:
dataset[0]

(array([1., 1., 4.]), array([], dtype=float64), array([1]), array([1, 0, 0]))

In [7]:

model = NeuralCF(dataset.data_schema)

In [8]:
u[0][:, 0]

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [9]:
model.criterion

MSELoss()

In [10]:
model(u[0])

tensor([[-0.0922],
        [-0.4535],
        [-0.1330],
        [ 0.4240],
        [-0.4979]], grad_fn=<AddmmBackward0>)

In [11]:
model.n_items

193609

In [12]:
movies.item.max()

193609

In [13]:
trainer = Trainer()
trainer.fit(model, train)

GPU available: True, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
/home/jiwidi/miniconda3/envs/cuda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1566: UserWarning: GPU available but not used. Set the gpus flag in your trainer `Trainer(gpus=1)` or script `--gpus=1`.
  rank_zero_warn(
/home/jiwidi/miniconda3/envs/cuda/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py:118: UserWarning: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
  rank_zero_warn("You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.")

  | Name           | Type      | Params
---------------------------------------------
0 | user_embedding | Embedding | 39.0 K
1 | item_embedding | Embedding | 12.4 M
2 | linear         | Linear    | 33.3 K
3 | final_linear   | Linear    | 513   
4 | criterion      | MSELoss   | 0     
---------------------------------------------
12.5

Training: 0it [00:00, ?it/s]

IndexError: index out of range in self

In [ ]:
import torch
x = torch.zeros(5, 1)
torch.squeeze(x).shape